# Generated by Django 4.0.3 on 2022-04-03 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='survey_pagea',
            new_name='survey_page',
        ),
    ]
