# Generated by Django 4.0.3 on 2022-04-03 18:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_rename_survey_pagea_survey_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey_page',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
