from cProfile import label
from fileinput import FileInput
from django.forms import ModelForm
from django import forms
from .models import Formulario

class FormularioForm(ModelForm):
  
    class Meta:
        client_choices = [('N','Nuevo'),('R','Renovacion'),]
        emision_choices = [('Solicitante','Solicitante'),('Otro','Otro'),]
        ramo_choices = (('vehiculo','VEHICULOS'),('vidagrupal','VIDA EN GRUPO'),('vidaindividuak','VIDA INDIVIDUAL'),('incendio','INCENDIO'),('transporte','TRANSPORTE'),('contratistas','CONTRATISTAS'),('casoaviones','CASCO DE AVIONES'),('accidentepersonal','ACCIDENTES PERSONALES'),('asistenciamedica','ASISTENCIA MEDICA'),('equipoelectronico','EQUIPO ELECTRONICO'),('robo','ROBO'),('responsabilidadcivil','RESPONSABILIDAD CIVIL'),('roturamaquinaria','ROTURA DE MAQUINARIA'),('cascobuque','CASCO DE BUQUE'),('cumplimientocontrato','CUMPLIMIENTO DE CONTRATO'),('fidelidad','FIDELIDAD'),('montajeriesgo','MONTAJE TODO RIESGO'),('salud','SALUD'),)
        sex_choices = (('M','M'),('F','F'),)
        boolean_choices = (('SI','SI'),('NO','NO'),)
        politic_choices = (('Comercial','Comercial'),('Contractual','Contractual'),('Laborales','Laborales'),('Otros','Otros'))
        canal_choices = (('DIRECTO','DIRECTO'),('BROKER','BROKER'),('OTROS','OTROS'))
        extra_choices = (('Familiar','Familiar'),('Broker','Broker'),('Otro','Otro'))
        civilstat_choices = (('Soltero','Soltero'),('Casado','Casado'),('Divorciado','Divorciado'),('U/Libre','U/Libre'),('Viudo','Viudo'),('Separado','Separado'),)
        typeid_choices = (('Cedula','Cedula'),('Pasaporte','Pasaporte'),('RUC','RUC'),)
        bond_choices = (('Familiar','Familiar'),('Comercial','Comercial'),('Laboral','Laboral'),('Ninguna','Ninguna'),('Otros','Otros'))
        vinculo_choices = (('Familiar','Familiar'),('Comercial','Comercial'),('Laboral','Laboral '),('Ninguna','Ninguna'), ('Otros', 'Otros'))
        work_choices = (('Empleado público','Empleado público'),('Empleado Privado','Empleado Privado'),('Negocio propio','Negocio propio'),('Jubilado','Jubilado'),('Estudiante','Estudiante'),('Quehaceres domésticos','Quehaceres domésticos'),('Otros','Otros'))
        prov_choices = (('AZUAY','AZUAY'),('BOLIVAR','BOLIVAR'),('CAÑAR','CAÑAR'),('CARCHI','CARCHI'),('CHIMBORAZO','CHIMBORAZO'),('COTOPAXI','COTOPAXI'),
        ('EL ORO','EL ORO'),('ESMERALDAS','ESMERALDAS'),('GALAPAGOS','GALAPAGOS'),('GUAYAS','GUAYAS'),('IMBABURA','IMBABURA'),('LOJA','LOJA'),('LOS RIOS','LOS RIOS'),
        ('MANABI','MANABI'),('MORRONA SANTIAGO','MORRONA SANTIAGO'),('NAPO','NAPO'),('ORELLANA','ORELLANA'),('PASTAZA','PASTAZA'),('PICHINCHA','PICHINCHA'),
        ('SANTA ELENA','SANTA ELENA'),('SANTO DOMINGO DE LOS TSACHILAS','SANTO DOMINGO DE LOS TSACHILAS'),('SUCUMBIOS','SUCUMBIOS'),('TUNGURAHUA','TUNGURAHUA'),
        ('ZAMORA CHINCHIPE','ZAMORA CHINCHIPE'),)
        place_choices = (('RESTO ZONAS','RESTO ZONAS'),('24 DE MAYO','24 DE MAYO'),('ALAMOR','ALAMOR'),('ALFREDO BAQUE','ALFREDO BAQUE'),('AMBATO','AMBATO'),('ARCHIDONA','ARCHIDONA'),('ARENILLAS','ARENILLAS'),('ATACAMES','ATACAMES'),('AYANGE','AYANGE'),(' AZOGUES',' AZOGUES'),('BABA','BABA'),('BABAHOYO','BABAHOYO'),('BAEZA','BAEZA'),('BAHIA DE CARA','BAHIA DE CARA'),
        ('BALAO','BALAO'),('BALSAS','BALSAS'),('BALZAR','BALZAR'),('BAÑOS','BAÑOS'),('BUCAY','BUCAY'),('BUENA FE','BUENA FE'),('CALUMA','CALUMA'),('CAMILO PONCE','CAMILO PONCE'),('CANUTO','CANUTO'),('CAYAMBE','CAYAMBE'),('CHAMBO','CHAMBO'),('CHIMBO','CHIMBO'),('CHONE','CHONE'),('CHUNCHI','CHUNCHI'),('COCA','COCA'),('COLIMES','COLIMES'),('CUENCA','CUENCA'),('DAULE','DAULE'),
        ('DURAN','DURAN'),('EL CARMEN','EL CARMEN'),('EL CHACO','EL CHACO'),('EL EMPALME','EL EMPALME'),('EL GUABO','EL GUABO'),('EL PLAYON','EL PLAYON'),('EL TRIUNFO','EL TRIUNFO'),('ESMERALDAS','ESMERALDAS'),('EL TRIUNFO','EL TRIUNFO'),('FLAVIO ALFARO','FLAVIO ALFARO'),('GALAPAGOS','GALAPAGOS'),('GUALACEO','GUALACEO'),('GUARANDA','GUARANDA'),('GUAYAQUIL','GUAYAQUIL'),
        ('HUAQUILLAS','HUAQUILLAS'),('IBARRA','IBARRA'),('ISIDRO AYORA','ISIDRO AYORA'),('JAMA','JAMA'),('JIPIJAPA','JIPIJAPA'),('JOYA DE LOS S','JOYA DE LOS S'),('JUJAN','JUJAN'),('JUNIN','JUNIN'),('LA MANA','LA MANA'),('LAGO AGRIO','LAGO AGRIO'),('LAS LAJAS','LAS LAJAS'),('LATACUNGA','LATACUNGA'),('LIBERTAD','LIBERTAD'),('LOJA','LOJA'),('LOMAS DE SARG','LOMAS DE SARG'),
        ('MACAS ','MACAS '),('MACHALA','MACHALA'),('MANTA','MANTA'),('MARCELINO MAR','MARCELINO MAR'),('MEJIA','MEJIA'),('MILAGRO','MILAGRO'),('MOCACHE','MOCACHE'),('MOLTALVO','MOLTALVO'),('MONTECRISTI','MONTECRISTI'),('MORONA','MORONA'),('NARANJAL','NARANJAL '),('NOBOL','NOBOL'),('OLMEDO','OLMEDO'),('OTAVALO','OTAVALO'),('OÑA','OÑA'),('PALENQUE','PALENQUE'),('PALESTINA','PALESTINA'),
        ('PALLATANGA','PALLATANGA'),('PAGUA','PAGUA'),('PASAJE','PASAJE'),('PATATE','PATATE'),('PAUTE','PAUTE'),('PEDERNALES','PEDERNALES'),('PEDRO CARBO','PEDRO CARBO'),('PELILEO','PELILEO'),('PIMAMPIRO','PIMAMPIRO'),('PIÑAS','PIÑAS'),('PLAYAS','PLAYAS'),('JUJAN','JUJAN'),('PORTOVELO','PORTOVELO'),('PORTOVIEJO','PORTOVIEJO'),('POSORJA','POSORJA'),('PTA. BARANDUA','PTA. BARANDUA'),
        ('PUEBLO VIEJO ','PUEBLO VIEJO '),('PUERTO AYORA','PUERTO AYORA'),('PUERTO VILLAM','PUERTO VILLAM'),('PUJILI','PUJILI'),('PUYANGO','PUYANGO'),('PUYO','PUYO '),('QUEVEDO','QUEVEDO'),('QUININDE','QUININDE'),('QUITO','QUITO'),('RIOBAMBA','RIOBAMBA'),('ROCAFUERTE','ROCAFUERTE'),('RUMIÑAHUI','RUMIÑAHUI'),('SALCEDO','SALCEDO'),('SALINAS','SALINAS'),('SALITRE','SALITRE'),
        ('SAN CRISTOBAL','SAN CRISTOBAL '),('SAN JOSE','SAN JOSE'),('SAN MIGUEL','SAN MIGUEL'),('SAN VICENTE','SAN VICENTE'),('SALGOLQUI','SALGOLQUI'),('SANTA ELENA','SANTA ELENA'),('SANTA ROSA','SANTA ROSA'),('SANTO DOMINGO','SANTO DOMINGO'),('SIG SIG','SIG SIG'),('SIMON BOLIVAR','SIMON BOLIVAR'),('STA. LUCIA','STA. LUCIA'),('STA. ROSA','STA. ROSA'),('TENA','TENA'),('TRIUNFO','TRIUNFO'),
        ('TULCAN','TULCAN'),('TUMBEZ','TUMBEZ'),('URDANETA','URDANETA'),('VALENCIA','VALENCIA'),('VENTANAS','VENTANAS'),('VINCES','VINCES'),('YAGUACHI','YAGUACHI'),('ZAMORA','ZAMORA'),('ZARUMA','ZARUMA'),)
        city_choices = (('AFG','AFGANISTAN'),('AX','ALAND'),('AL','ALBANIA'),('DEU','ALEMANIA'),('AD','ANDORRA'),('AO','ANGOLA'),('AI','ANGUILA'),('AQ','ANTARTIDA'),('AG','ANTIGUA Y BARBUDA'),('AN','ANTILLAS NEERLANDESAS'),('SA','ARABIA SAUDITA'),('DZ','ARGELIA'),('ARP','ARGENTINA'),('AM','ARMENIA'),('AW','ARUBA'),('AUD','AUSTRALIA'),('AT','AUSTRIA'),('AZ','AZERBAIYAN'),
            ('BS','BAHAMAS'),('BH','BAHREIN'),('BB','BARBADOS'),('BLR','BELARAUS'),('BE','BELGICA'),('BZ','BELICE'),('BJ','BENIN'),('BM','BERMUDAS'),('BY','BIELORRUSIA'),('MMR','BIRMANIA'),('BOL','BOLIVIA'),('BA','BOSNIA Y HERZEGOVINA'),('BW','BOTSUANA'),('BRC','BRASIL'),('BN','BRUNEI'),('BG','BULGARIA'),('BF','BURKINA FASO'),('BDI','BURUNDI'),('BT','BUTAN'),
            ('CV','CABO VERDE'),('KH','CAMBOYA'),('CM','CAMERUN'),('CAD','CANADA'),('TD','CHAD'),('CLP','CHILE'),('CHN','CHINA'),('CY','CHIPRE'),('VA','CIUDAD DEL VATICANO'),('COP','COLOMBIA'),('KM','COMORAS'),('PRK','COREA DEL NORTE'),('KR','COREA DEL SUR'),('CIV','COSTA DE MARFIL'),('CR','CRIMEA'),('HR','CROACIA'),('CUP','CUBA'),('DKK','DINAMARCA'),('DM','DOMINICA'),
            ('ECS','ECUADOR'),('EG','EGIPTO'),('SV','EL SALVADOR'),('AE','EMIRATOS ARABES UNIDOS'),('ERI','ERITREA'),('SK','ESLOVAQUIA'),('SI','ESLOVENIA'),('ESP','ESPA¥A'),('USA','ESTADOS UNIDOS'),('EE','ESTONIA'),('ET','ETIOPIA'),('PH','FILIPINAS'),('FI','FINLANDIA'),('FJ','FIYI'),('FRP','FRANCIA'),('GA','GABON'),('GM','GAMBIA'),('GE','GEORGIA'),('GH','GHANA'),('GD','GRANADA'),
            ('GR','GRECIA'),('GL','GROENLANDIA'),('GP','GUADALUPE'),('GU','GUAM'),('GTQ','GUATEMALA'),('GF','GUAYANA FRANCESA'),('GG','GUERNSEY'),('GIN','GUINE'),('GQ','GUINEA ECUATORIAL'),('GNB','GUINEA-BISSAU'),('GY','GUYANA'),('HTI','HAITI'),('NLG','HOLANDA'),('HN','HONDURAS'),('HK','HONG KONG'),('HU','HUNGRIA'),('IN','INDIA'),('ID','INDONESIA'),('ING','INGLATERRA'),
            ('IRR','IRAN'),('IRQ','IRAQ'),('IE','IRLANDA'),('BV','ISLA BOUVET'),('IM','ISLA DE MAN'),('CX','ISLA DE NAVIDAD'),('IS','ISLANDIA'),('KY','ISLAS CAIMáN'),('CC','ISLAS COCOS'),('CK','ISLAS COOK'),('FO','ISLAS FEROE'),('GS','ISLAS GEORGIAS DEL SUR Y SANDWICH DEL SUR'),('HM','ISLAS HEARD Y MCDONALD'),('FK','ISLAS MALVINAS'),('MP','ISLAS MARIANAS DEL NORTE'),
            ('MH','ISLAS MARSHALL'),('PN','ISLAS PITCAIRN'),('SB','ISLAS SALOMON'),('TC','ISLAS TURCAS Y CAICOS'),('UM','ISLAS ULTRAMARINAS DE ESTADOS UNIDOS'),('VG','ISLAS VIRGENES BRITANICAS'),('VI','ISLAS VIRGENES ESTADOUNIDENSES'),('IL','ISRAEL'),('ITA','ITALIA'),('JM','JAMAICA'),('JP','JAPON'),('JE','JERSEY'),('JO','JORDANIA'),('KZ','KAZAJISTAN'),('KE','KENIA'),
            ('KG','KIRGUISTAN'),('KI','KIRIBATI'),('KW','KUWAIT'),('LA','LAOS'),('LS','LESOTO'),('LV','LETONIA'),('LBN','LIBANO'),('LR','LIBERIA'),('LBY','LIBIA'),('LI','LIECHTENSTEIN'),('LT','LITUANIA'),('LU','LUXEMBURGO'),('MO','MACAO'),('MK','MACEDONIA'),('MG','MADAGASCAR'),('MY','MALASIA'),('MW','MALAUI'),('MV','MALDIVAS'),('MLI','MALI'),('MT','MALTA'),('MA','MARRUECOS'),
            ('MQ','MARTINICA'),('MU','MAURICIO'),('MR','MAURITANIA'),('YT','MAYOTTE'),('MXP','MEXICO'),('FM','MICRONESIA'),('MD','MOLDAVIA'),('MC','MONACO'),('MN','MONGOLIA'),('ME','MONTENEGRO'),('MS','MONTSERRAT'),('MZ','MOZAMBIQUE'),('MMR','MYANMAR'),('NA','NAMIBIA'),('NR','NAURU'),('NP','NEPAL'),('NIC','NICARAGUA'),('NE','NIGER'),('NG','NIGERIA'),('NU','NIUE'),('NF','NORFOLK'),
            ('NO','NORUEGA'),('NC','NUEVA CALEDONIA'),('NZ','NUEVA ZELANDA'),('OM','OMAN'),('NLD','PAISES BAJOS'),('PAK','PAKISTAN'),('PW','PALAOS'),('PAB','PANAMA'),('PG','PAPUA NUEVA GUINEA'),('PY','PARAGUAY'),('PES','PERU'),('PF','POLINESIA FRANCESA'),('PL','POLONIA'),('PT','PORTUGAL'),('QA','QATAR'),('GBR','REINO UNIDO'),('COD','REP.DEMOCRATICA DEL CONGLO'),
            ('CAF','REPUBLICA CENTROAFRICANA'),('CF','REPUBLICA CENTROAFRICANA'),('CZ','REPúBLICA CHECA'),('CG','REPUBLICA DEL CONGO'),('CD','REPUBLICA DEMOCRATICA'),('DO','REPUBLICA DOMINICANA'),('RE','REUNION'),('RW','RUANDA'),('ROS','RUMANIA'),('RUS','RUSIA'),('EH','SAHARA OCCIDENTAL'),('AS','SAMOA AMERICANA'),('BL','SAN BARTOLOMé'),('KN','SAN CRISTOBAL Y NIEVES'),('SM','SAN MARINO'),
            ('PM','SAN PEDRO Y MIQUELON'),('VC','SAN VICENTE Y LAS GRANADINAS'),('SH','SANTA HELENA'),('LC','SANTA LUCIA'),('ST','SANTO TOME Y PRINCIPE'),('SN','SENEGAL'),('RS','SERBIA'),('SC','SEYCHELLES'),('SL','SIERRA LEONA'),('SG','SINGAPUR'),('SYR','SIRIA'),('SOM','SOMALIA'),('SSD','SOUTH SUDAN'),('LK','SRI LANKA'),('SZ','SUAZILANDIA'),('ZA','SUDAFRICA'),
            ('SDN','SUDAN'),('SEK','SUECIA'),('CHF','SUIZA'),('SR','SURINAM'),('SJ','SVALBARD Y JAN MAYEN'),('TH','TAILANDIA'),('TW','TAIWAN'),('TZ','TANZANIA'),('TJ','TAYIKISTAN'),('IO','TERRITORIO BRITáNICO DEL OCéANO ÍNDICO'),('TF','TERRITORIOS AUSTRALES FRANCESES'),('PS','TERRITORIOS PALESTINOS'),('TL','TIMOR ORIENTAL'),('TG','TOGO'),('TK','TOKELAU'),('TO','TONGA'),
            ('TT','TRINIDAD Y TOBAGO'),('TN','TUNEZ'),('TM','TURKMENISTAN'),('TR','TURQUIA'),('TV','TUVALU'),('UKR','UCRANIA'),('UG','UGANDA'),('EU','UNION EUROPEA'),('SU','UNION SOVIETICA'),('UZ','URBEKISTAN'),('UYP','URUGUAY'),('VU','VANUATU'),('VEB','VENEZUELA'),('VN','VIETNAM'),('WF','WALLIS Y FUTUNA'),('YEM','YEMEN'),('DJ','YIBUTI'),('ZM','ZAMBIA'),('ZWE','ZIMBABUE'),)
        model = Formulario
        fields = '__all__'
        labels = {
            'cliente':'CLIENTE',
            'tiposeguro' :'Tipo de Seguro (Ramo)',
            'sumasegurada':'Total Suma Asegurada USD',
            'doc_solicit':'Tipo de ID',
            'num_solicit':'Número de ID',
            'apell_solicit':'Apellidos',
            'name_solicit':'Nombres',
            'sex_solicit':'Sexo',
            'state_solicit':'Estado Civil',
            'nacim_solicit':'Lugar de Nacimiento',
            'datenacim_solict':'Fecha de Nacimiento',
            'nacion_solicit':'Nacionalidad:',
            'domic_solict':'Domicilio',
            'ciud_solicit':'Ciudad',
            'pais_solicit':'País',
            'prov_solicit':'Provincia',
            'tel_solicit':'Telefonos',
            'mail_solicit':'E-mail',
            'mail_fact_solicit':'Mail para  recibir Factura Electrónica',
            'mail_form_solicit':'Mail  para recibir el Formulario de Retención',
            'contac_solicit':'Persona de Contacto (Nombre y Apellido):',
            'doc_conv':'Tipo de ID',
            'num_conv':'Número de ID:',
            'apell_conv':'Apellidos',
            'name_conv':'Nombres',
            'vinc_asegur':'VÍNCULO',
            'specif_asegur':'Especifique',
            'doc_asegur':'Tipo de ID',
            'num_asegur':'Número de ID',
            'apell_asegur':'Apellidos',
            'name_asegur':'Nombres',
            'sex_asegur':'Sexo',
            'state_asegur':'Estado Civil',
            'nacim_asegur':'Lugar de Nacimiento',
            'datenacim_asegur':'Fecha de Nacimiento',
            'nacion_asegur':'Nacionalidad',
            'domic_asegur':'Dirección de domicilio',
            'tel_asegur':'Teléfono',
            'mail_asegur':'Email',
            'vinc_benefic':'VÍNCULO',
            'specif_benefic':'Especifique',
            'doc_benefic':'Tipo de ID',
            'num_benefic':'Número de ID',
            'apell_benefic':'Apellidos',
            'name_benefic':'Nombres',
            'sex_benefic':'Sexo',
            'state_benefic':'Estado Civil',
            'nacim_benefic':'Lugar de Nacimiento',
            'datenacim_benefic':'Fecha de Nacimiento',
            'nacion_benefic':'Nacionalidad',
            'domic_benefic':'Dirección de domicilio',
            'tel_benefic':'Teléfono',
            'mail_benefic':'Email',
            #'type_work':'tipo trabajo',
            'especify_work':'Especifique',
            'razon_work':'Nombre o Razón Social  Lugar de trabajo',
            'sector_work':'Sector',
            'activity_work':'Actividad',
            'cargo_work':'Cargo que desempeña',
            'domic_work':'Dirección de trabajo',
            'city_work':'País',
            'ciud_work':'Ciudad',
            'mail_work':'Correo electrónico',
            'tel_work':'teléfono',
            'ingress_info':'Detalle de  ingresos mensuales de actividad declarada:  USD',
            'mesuality_info':'Detalle de  ingresos mensuales USD',
            'other_info':'Fuente de los otros ingresos',
            'activos_info':'Total de Activos',
            'pasivos_info':'Total de Pasivos',
            'patrim_info':'Patrimonio',
            'name_reference':'Nombre y Apellido',
            'parentesc_reference':'Parentesco',
            'tel_reference':'teléfono',
            'target_reference':'Tarjeta',
            'instfin_reference':'Inst. Financiera',
            'ctatype_reference':'Tipo cta. Ahorro /corriente',
            'instbanc_reference':'Inst. Financiera',
            'nameoth_reference':'Nombre y Apellido',
            'parentescoth_reference':'Parentesco',
            'teloth_reference':'teléfono',
            'targetoth_reference':'Tarjeta',
            'instfinoth_reference':'Inst. Financiera',
            'ctatypeoth_reference':'Tipo cta. Ahorro /corriente',
            'instbancoth_reference':'Inst. Financiera',
            #'emision_factur':,
            'social_factur':'Nombre/ Razón social',
            'rucci_factur':'C.I/Ruc No.',
            'tel_factur':'Teléfono',
            'domic_factur':'Dirección',
            'relacion_factur':'Relación con el Solicitante',
            'names_extra':'Nombres y Apellidos',
            #'adicionch_extra':,
            #'specific_extra':'Especifique',
            #'func_extra':'',
            'cargo_extra_decl': 'Indicar: Cargo / Función / Jerarquía o relación con la Persona Expuesta Políticamente',
            'datenacim_decl': 'Fecha del nombramiento de designación',
            'datenacim_extra_decl': 'Fecha de culminación del cargo, en caso de aplicar',
            'politic_decl': 'Adicionalmente, declaro que mantengo relación tipo',
            'specif_decl': 'Especifique Relación',
            'con_decl': 'Con',
            #'canal_extra':,
            #'ced_file':,
            #'serbas_file':,
            #'conv_file':,
            #'cert_file':,
            #'cargo_file':,
            #'renta_file':,
            'lugar_declaration':'Lugar',
            'condic_declaration':'¿Esta de acuerdo con las condiciones?',
        }
        widgets={
            'cliente': forms.RadioSelect(choices=client_choices),
            'tiposeguro': forms.Select(choices=ramo_choices),
            'sumasegurada': forms.NumberInput(),
            'doc_solicit': forms.RadioSelect(choices = typeid_choices),
            'num_solicit':forms.NumberInput(),
            'apell_solicit': forms.TextInput(),
            'name_solicit': forms.TextInput(),
            'sex_solicit': forms.RadioSelect(choices=sex_choices),
            'state_solicit': forms.RadioSelect(choices=civilstat_choices),
            'nacim_solicit': forms.TextInput(),
            'datenacim_solict': forms.DateInput(attrs={'type':'date'}),
            'nacion_solicit': forms.TextInput(),
            'domic_solict': forms.TextInput(),
            'ciud_solicit': forms.TextInput(),
            'pais_solicit': forms.Select(choices=city_choices),
            'prov_solicit': forms.Select(choices=prov_choices),
            'tel_solicit': forms.TextInput(),
            'mail_solicit': forms.EmailInput(),
            'mail_fact_solicit': forms.EmailInput(),
            'mail_form_solicit': forms.EmailInput(),
            'contac_solicit': forms.TextInput(),
            'doc_conv': forms.RadioSelect(choices=typeid_choices),
            'num_conv': forms.NumberInput(),
            'apell_conv': forms.TextInput(),
            'name_conv': forms.TextInput(),
            'vinc_asegur': forms.RadioSelect(choices=bond_choices),
            'specif_asegur': forms.TextInput(),
            'doc_asegur': forms.RadioSelect(choices = typeid_choices),
            'num_asegur': forms.NumberInput(),
            'apell_asegur': forms.TextInput(),
            'name_asegur': forms.TextInput(),
            'sex_asegur': forms.RadioSelect(choices=sex_choices),
            'state_asegur': forms.RadioSelect(choices=civilstat_choices),
            'nacim_asegur': forms.TextInput(),
            'datenacim_asegur': forms.DateInput(attrs={'type':'date'}),
            'nacion_asegur': forms.TextInput(),
            'domic_asegur':forms.TextInput(),
            'tel_asegur': forms.NumberInput(),
            'mail_asegur': forms.EmailInput(),
            'vinc_benefic': forms.RadioSelect(choices=bond_choices),
            'specif_benefic': forms.TextInput(),
            'doc_benefic': forms.RadioSelect(choices = typeid_choices),
            'num_benefic': forms.NumberInput(),
            'apell_benefic': forms.TextInput(),
            'name_benefic': forms.TextInput(),
            'sex_benefic': forms.RadioSelect(choices=sex_choices),
            'state_benefic': forms.RadioSelect(choices=civilstat_choices),
            'nacim_benefic': forms.TextInput(),
            'datenacim_benefic': forms.DateInput(attrs={'type':'date'}),
            'nacion_benefic': forms.TextInput(),
            'domic_benefic': forms.TextInput(),
            'tel_benefic': forms.NumberInput(),
            'mail_benefic': forms.EmailInput(),
            'type_work': forms.RadioSelect(choices=work_choices),
            'especify_work': forms.TextInput(),
            'razon_work': forms.TextInput(),
            'sector_work': forms.TextInput(),
            'activity_work': forms.TextInput(),
            'cargo_work': forms.TextInput(),
            'domic_work': forms.TextInput(),
            'city_work': forms.Select(choices=city_choices),
            'ciud_work': forms.TextInput(),
            'mail_work': forms.EmailInput(),
            'tel_work': forms.NumberInput(),
            'ingress_info': forms.NumberInput(),
            'mesuality_info': forms.NumberInput(),
            'other_info': forms.NumberInput(),
            'activos_info': forms.NumberInput(),
            'pasivos_info': forms.NumberInput(),
            'patrim_info': forms.NumberInput(),
            'name_reference': forms.TextInput(),
            'parentesc_reference': forms.TextInput(),
            'tel_reference': forms.NumberInput(),
            'target_reference': forms.NumberInput(),
            'instfin_reference': forms.TextInput(),
            'ctatype_reference': forms.NumberInput(),
            'instbanc_reference': forms.TextInput(),
            'nameoth_reference': forms.TextInput(),
            'parentescoth_reference': forms.TextInput(),
            'teloth_reference': forms.NumberInput(),
            'targetoth_reference': forms.NumberInput(),
            'instfinoth_reference': forms.TextInput(),
            'ctatypeoth_reference': forms.NumberInput(),
            'instbancoth_reference': forms.TextInput(),
            'emision_factur': forms.RadioSelect(choices=emision_choices),
            'social_factur': forms.TextInput(),
            'rucci_factur': forms.NumberInput(),
            'tel_factur': forms.NumberInput(),
            'domic_factur': forms.TextInput(),
            'relacion_factur': forms.TextInput(),
            'names_extra': forms.TextInput(),
            'adicionch_extra': forms.Select(choices=extra_choices),
            'specific_extra': forms.TextInput(),
            'func_extra': forms.Select(choices=boolean_choices),
            'cargo_extra_decl': forms.TextInput(),
            'datenacim_decl': forms.DateInput(attrs={'type':'date'}),
            'datenacim_extra_decl': forms.DateInput(attrs={'type':'date'}),
            'politic_decl': forms.Select(choices=politic_choices),
            'specif_decl': forms.TextInput(),
            'con_decl': forms.TextInput(),

            'canal_extra': forms.Select(choices=canal_choices),
            'ced_file': forms.FileInput(),
            'serbas_file': forms.FileInput(),
            'conv_file': forms.FileInput(),
            'cert_file': forms.FileInput(),
            'cargo_file': forms.FileInput(),
            'renta_file': forms.FileInput(),
            'lugar_declaration': forms.Select(choices=place_choices),
            'condic_declaration': forms.CheckboxInput(),
        }
    
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)