# Generated by Django 4.0.3 on 2022-04-20 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=200)),
                ('tiposeguro', models.CharField(max_length=200)),
                ('sumasegurada', models.IntegerField()),
                ('doc_solicit', models.CharField(max_length=200)),
                ('num_solicit', models.IntegerField()),
                ('apell_solicit', models.CharField(max_length=200)),
                ('name_solicit', models.CharField(max_length=200)),
                ('sex_solicit', models.CharField(max_length=200)),
                ('state_solicit', models.CharField(max_length=200)),
                ('nacim_solicit', models.CharField(max_length=200)),
                ('datenacim_solict', models.CharField(max_length=200)),
                ('nacion_solicit', models.CharField(max_length=200)),
                ('domic_solicit', models.CharField(max_length=200)),
                ('ciud_solicit', models.CharField(max_length=200)),
                ('pais_solicit', models.CharField(max_length=200)),
                ('prov_solicit', models.CharField(max_length=200)),
                ('tel_solicit', models.CharField(max_length=200)),
                ('mail_solicit', models.CharField(max_length=200)),
                ('mail_fact_solicit', models.CharField(max_length=200)),
                ('mail_form_solicit', models.CharField(max_length=200)),
                ('contac_solicit', models.CharField(max_length=200)),
                ('doc_conv', models.CharField(max_length=200)),
                ('num_conv', models.CharField(max_length=200)),
                ('apell_conv', models.CharField(max_length=200)),
                ('name_conv', models.CharField(max_length=200)),
                ('vinc1_asegur', models.CharField(max_length=200)),
                ('vinc2_asegur', models.CharField(max_length=200)),
                ('doc_asegur', models.CharField(max_length=200)),
                ('num_asegur', models.CharField(max_length=200)),
                ('apell_asegur', models.CharField(max_length=200)),
                ('name_asegur', models.CharField(max_length=200)),
                ('sex_asegur', models.CharField(max_length=200)),
                ('state_asegur', models.CharField(max_length=200)),
                ('nacim_asegur', models.CharField(max_length=200)),
                ('datenacim_asegur', models.CharField(max_length=200)),
                ('nacion_asegur', models.CharField(max_length=200)),
                ('domic_asegur', models.CharField(max_length=200)),
                ('tel_asegur', models.CharField(max_length=200)),
                ('mail_asegur', models.CharField(max_length=200)),
                ('vinc1_benefic', models.CharField(max_length=200)),
                ('vinc2_benefic', models.CharField(max_length=200)),
                ('doc_benefic', models.CharField(max_length=200)),
                ('num_benefic', models.IntegerField()),
                ('apell_benefic', models.CharField(max_length=200)),
                ('name_benefic', models.CharField(max_length=200)),
                ('sex_benefic', models.CharField(max_length=200)),
                ('state_benefic', models.CharField(max_length=200)),
                ('nacim_benefic', models.CharField(max_length=200)),
                ('datenacim_benefic', models.CharField(max_length=200)),
                ('nacion_benefic', models.CharField(max_length=200)),
                ('domic_benefic', models.CharField(max_length=200)),
                ('tel_benefic', models.CharField(max_length=200)),
                ('mail_benefic', models.CharField(max_length=200)),
                ('type_economy', models.CharField(max_length=200)),
                ('especify_economy', models.CharField(max_length=200)),
                ('razon_social', models.CharField(max_length=200)),
            ],
        ),
    ]
