# Generated by Django 4.0.3 on 2022-04-19 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(choices=[('N', 'Nuevo'), ('R', 'Renovacion')], max_length=200, verbose_name='cliente')),
                ('tiposeguro', models.CharField(choices=[('vehiculo', 'VEHICULOS'), ('vidagrupal', 'VIDA EN GRUPO'), ('vidaindividuak', 'VIDA INDIVIDUAL'), ('incendio', 'INCENDIO'), ('transporte', 'TRANSPORTE'), ('contratistas', 'CONTRATISTAS'), ('casoaviones', 'CASCO DE AVIONES'), ('accidentepersonal', 'ACCIDENTES PERSONALES'), ('asistenciamedica', 'ASISTENCIA MEDICA'), ('equipoelectronico', 'EQUIPO ELECTRONICO'), ('robo', 'ROBO'), ('responsabilidadcivil', 'RESPONSABILIDAD CIVIL'), ('roturamaquinaria', 'ROTURA DE MAQUINARIA'), ('cascobuque', 'CASCO DE BUQUE'), ('cumplimientocontrato', 'CUMPLIMIENTO DE CONTRATO'), ('fidelidad', 'FIDELIDAD'), ('montajeriesgo', 'MONTAJE TODO RIESGO'), ('salud', 'SALUD')], max_length=200)),
                ('sumasegurada', models.IntegerField()),
                ('doc_solicit', models.CharField(choices=[('Cedula', 'Cedula'), ('Pasaporte', 'Pasaporte'), ('RUC', 'RUC')], max_length=200)),
                ('num_solicit', models.IntegerField()),
                ('apell_solicit', models.CharField(max_length=200)),
                ('name_solicit', models.CharField(max_length=200)),
                ('sex_solicit', models.CharField(choices=[('M', 'M'), ('F', 'F')], max_length=200)),
            ],
        ),
    ]
